development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: bonebreak1
  database: gpsmytruck_development
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: bonebreak1
  database: gpsmytruck_test        # or whatever the name is
  encoding: UTF8

production:
  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5